name: Deploy Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build guc for USD v22.11
    uses: ./.github/workflows/build-usd22.11.yml
    with:
      build-config: Release

  deploy-release:
    name: Deploy Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.archive-name }}

      - name: Deploy draft release
        uses: softprops/action-gh-release@v1
        with:
          name: "Version XXX"
          body: "TBD"
          files: |
            */*.tar.gz
          fail_on_unmatched_files: true
          draft: true
